In [131]:
import random
import pandas as pd
import numpy as np
import datetime

import matplotlib.pyplot as plt

In [132]:
def generate_random_numbers(n, lower_bound, upper_bound):
    random_numbers = [random.randint(lower_bound, upper_bound) for _ in range(n)]
    return random_numbers
def generate_random_floats(n, lower_bound, upper_bound):
    random_numbers = [random.uniform(lower_bound, upper_bound) for _ in range(n)]
    return random_numbers
def random_float_near_n(n, range_width=1.0):
    # Calculate the lower and upper bounds of the range
    lower_bound = n - (range_width / 2)
    upper_bound = n + (range_width / 2)

    # Generate a random float within the specified range
    return random.uniform(lower_bound, upper_bound)

In [133]:


def generate_one_year_time_series_with_factors(initial_connection,final_connection, factors, start_year, freq='D'):
    
    if len(factors) != 3:
        raise ValueError("Factors array must contain exactly 3 elements.")

    # Calculate the start and end dates for one year
    start_date = datetime.date(start_year, 1, 1)
    end_date = datetime.date(start_year, 12, 31)

    # Create a date range based on the start_date, end_date, and frequency
    date_range = pd.date_range(start=start_date, end=end_date, freq=freq)
    connections=generate_random_numbers(len(date_range),initial_connection,final_connection)
    
    # Initialize an empty DataFrame
    df = pd.DataFrame({'Date': date_range})

    # Calculate the number of time steps in each segment
    num_steps_per_segment = len(date_range) // 3

    # Initialize the factor index and population
    factor_index = 0
    # initial_factors = generate_random_floats(num_steps_per_segment,factors[0]);

    # Generate population values based on the segmented factors
    connections.sort()
    populations = []
    actual_limits=[]
    supply =[]
    factor=[]

    for i in range(len(date_range)):
        populations.append((int)(connections[i]*4.799))
        actual_limits.append(populations[i]*135)
        factor.append(random_float_near_n(factors[factor_index],0.09))
        supply.append(populations[i]*(135*factor[i]))

        # Move to the next factor segment when needed
        if (i + 1) % num_steps_per_segment == 0 and factor_index < 2:
            factor_index += 1

    # Add the population values to the DataFrame
    df['connection']=connections
    df['population']=populations
    df['actual_limit']=actual_limits
    df['factor']=factor
    df['consumption']=supply
    existing_csv_filename = 'time_series_data.csv'
    existing_data = pd.read_csv(existing_csv_filename)

    # Concatenate the existing data and the additional data
    combined_data = pd.concat([existing_data, df], ignore_index=True)

    # Save the combined data back to the CSV file (mode='w' overwrites, mode='a' appends)
    combined_data.to_csv(existing_csv_filename, index=False, mode='a', header=False)
    return df

In [134]:
# generate_one_year_time_series_with_factors(4728,4962,[1.2,1.16,1.09],2020)

Date,connection,population,actual_limit,factor,consumption

In [135]:


# # Assuming you have loaded your DataFrame 'df' already

# # Convert the 'Date' column to datetime if it's not already
# df['Date'] = pd.to_datetime(df['Date'])

# # Create a line plot
# plt.figure(figsize=(12, 6))  # Adjust the figure size as needed
# plt.plot(df['Date'], df['consumption'], marker='o', linestyle='-')
# plt.title('Consumption Over Time')
# plt.xlabel('Date')
# plt.ylabel('Consumption')
# plt.grid(True)

# # Rotate x-axis labels for better readability (optional)
# plt.xticks(rotation=45)

# # Show the plot
# plt.tight_layout()
# plt.show()

In [136]:
# generate_one_year_time_series_with_factors(4037,4254,[1.1528,1.1948,1.075],2017)
# generate_one_year_time_series_with_factors(4254,4502,[1.1563,1.1962,1.079],2018)
# generate_one_year_time_series_with_factors(4502,4728,[1.1597,1.1989,1.0885],2019)
# generate_one_year_time_series_with_factors(4728,4962,[1.16,1.2,1.09],2020)
generate_one_year_time_series_with_factors(4962,5172,[1.162,1.209,1.095],2021)

          Date  connection  population  actual_limit    factor   consumption
0   2021-01-01        4962       23812       3214620  1.196174  3.845245e+06
1   2021-01-02        4964       23822       3215970  1.123770  3.614011e+06
2   2021-01-03        4965       23827       3216645  1.201793  3.865742e+06
3   2021-01-04        4965       23827       3216645  1.172831  3.772579e+06
4   2021-01-05        4966       23831       3217185  1.168712  3.759964e+06
..         ...         ...         ...           ...       ...           ...
360 2021-12-27        5170       24810       3349350  1.087424  3.642164e+06
361 2021-12-28        5170       24810       3349350  1.114535  3.732967e+06
362 2021-12-29        5171       24815       3350025  1.065369  3.569011e+06
363 2021-12-30        5172       24820       3350700  1.069975  3.585165e+06
364 2021-12-31        5172       24820       3350700  1.079219  3.616139e+06

[365 rows x 6 columns]